#Properties for Config Server
owner: honeymon
blog:
  github: http://honeymon.io
  java: http://java.ihoney.pe.kr
  life: http://ihoney.pe.kr

---

spring:
    profiles: dev
app:
    profile: dev

---

spring:
    prfiles: prd
app:
    profile: prd
